25 cant define or retreive the session
montevideo-tech/videojs-cmcd pull request #28
Opened 2023-06-08 20:53 UTC by coatesjuan

2023-06-09 16:13 UTC, JoaquinBCh requested changes
Add an explanation of the funtionality to the readme

2023-06-13 19:01 UTC, adriansqualabs approved these changes

2023-06-13 19:02 UTC, adriansqualabs requested changes
You have some ci/cd issues to fix.

2023-06-14 14:59 UTC, mcamardon approved these changes

2023-06-14 15:02 UTC, adriansqualabs approved these changes

2023-06-14 16:30 UTC, merged