21 bug not sending cmcd data on manifest request
montevideo-tech/videojs-cmcd pull request #32
Opened 2023-07-03 19:47 UTC by coatesjuan

2023-07-04 19:56 UTC, mcamardon approved these changes

2023-07-05 18:41 UTC, nicolaslevy requested changes
We should add something in the README explaining how to retrieve sessionid and contentid

2023-07-05 18:41 UTC, nicolaslevy commented on README.md
We should add something explaining how to retrieve sessionid and contentid

2023-07-05 18:49 UTC, nicolaslevy requested changes

2023-07-05 18:49 UTC, nicolaslevy commented on README.md
> +
and how do I know those values? ;)  player.cmcd().sid ? player.cmcd().getId().sid ?

2023-07-06 15:09 UTC, nicolaslevy approved these changes
Great job @coatesjuan :clap:

2023-07-06 15:11 UTC, merged